# Generated by Django 4.1.4 on 2023-01-10 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_order_product_productorder_order_products_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="productorder", name="in_order",),
        migrations.RemoveField(model_name="productorder", name="product",),
        migrations.DeleteModel(name="Order",),
        migrations.DeleteModel(name="Product",),
        migrations.DeleteModel(name="ProductOrder",),
        migrations.DeleteModel(name="Staff",),
    ]
